In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('AB_NYC_2019.csv')
df.head()
df.T

,0,1,2,3,4,5,6,7,8,9,...,48885,48886,48887,48888,48889,48890,48891,48892,48893,48894
id,2539,2595,3647,3831,5022,5099,5121,5178,5203,5238,...,36482809,36483010,36483152,36484087,36484363,36484665,36485057,36485431,36485609,36487245
name,Clean & quiet apt home by the park,Skylit Midtown Castle,THE VILLAGE OF HARLEM....NEW YORK !,Cozy Entire Floor of Brownstone,Entire Apt: Spacious Studio/Loft by central park,Large Cozy 1 BR Apartment In Midtown East,BlissArtsSpace!,Large Furnished Room Near B'way,Cozy Clean Guest Room - Family Apt,Cute & Cozy Lower East Side 1 bdrm,...,Stunning Bedroom NYC! Walking to Central Park!!,Comfy 1 Bedroom in Midtown East,Garden Jewel Apartment in Williamsburg New York,"Spacious Room w/ Private Rooftop, Central loca...",QUIT PRIVATE HOUSE,Charming one bedroom - newly renovated rowhouse,Affordable room in Bushwick/East Williamsburg,Sunny Studio at Historical Neighborhood,43rd St. Time Square-cozy single bed,Trendy duplex in the very heart of Hell's Kitchen
host_id,2787,2845,4632,4869,7192,7322,7356,8967,7490,7549,...,131529729,274311461,208514239,274321313,107716952,8232441,6570630,23492952,30985759,68119814
host_name,John,Jennifer,Elisabeth,LisaRoxanne,Laura,Chris,Garon,Shunichi,MaryEllen,Ben,...,Kendall,Scott,Melki,Kat,Michael,Sabrina,Marisol,Ilgar & Aysel,Taz,Christophe
neighbourhood_group,Brooklyn,Manhattan,Manhattan,Brooklyn,Manhattan,Manhattan,Brooklyn,Manhattan,Manhattan,Manhattan,...,Manhattan,Manhattan,Brooklyn,Manhattan,Queens,Brooklyn,Brooklyn,Manhattan,Manhattan,Manhattan
neighbourhood,Kensington,Midtown,Harlem,Clinton Hill,East Harlem,Murray Hill,Bedford-Stuyvesant,Hell's Kitchen,Upper West Side,Chinatown,...,East Harlem,Midtown,Williamsburg,Hell's Kitchen,Jamaica,Bedford-Stuyvesant,Bushwick,Harlem,Hell's Kitchen,Hell's Kitchen
latitude,40.64749,40.75362,40.80902,40.68514,40.79851,40.74767,40.68688,40.76489,40.80178,40.71344,...,40.79633,40.75561,40.71232,40.76392,40.69137,40.67853,40.70184,40.81475,40.75751,40.76404
longitude,-73.97237,-73.98377,-73.9419,-73.95976,-73.94399,-73.975,-73.95596,-73.98493,-73.96723,-73.99037,...,-73.93605,-73.96723,-73.9422,-73.99183,-73.80844,-73.94995,-73.93317,-73.94867,-73.99112,-73.98933
room_type,Private room,Entire home/apt,Private room,Entire home/apt,Entire home/apt,Entire home/apt,Private room,Private room,Private room,Entire home/apt,...,Private room,Entire home/apt,Entire home/apt,Private room,Private room,Private room,Private room,Entire home/apt,Shared room,Private room
price,149,225,150,89,80,200,60,79,79,150,...,75,200,170,125,65,70,40,115,55,90
minimum_nights,1,1,3,1,10,3,45,2,2,1,...,2,6,1,4,1,2,4,10,1,7
number_of_reviews,9,45,0,270,9,74,49,430,118,160,...,0,0,0,0,0,0,0,0,0,0
last_review,2018-10-19,2019-05-21,NaN,2019-07-05,2018-11-19,2019-06-22,2017-10-05,2019-06-24,2017-07-21,2019-06-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reviews_per_month,0.21,0.38,NaN,4.64,0.1,0.59,0.4,3.47,0.99,1.33,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
calculated_host_listings_count,6,2,1,1,1,1,1,1,1,4,...,2,1,3,1,2,2,2,1,6,1
availability_365,365,355,365,194,0,129,0,220,0,188,...,353,176,365,31,163,9,36,27,2,23

In [3]:
df.price = np.log1p(df.price)

In [4]:
categorical = list(df.dtypes[df.dtypes == object].index)
numerical = list(df.dtypes[df.dtypes != object].index)

In [5]:
df.isnull().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
dtype: int64

In [6]:
df[numerical] = df[numerical].fillna(0)
df[categorical] = df[categorical].fillna('')

In [7]:
df.isnull().sum()

id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood_group               0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)

In [10]:
len(df_full_train), len(df_test)

(39116, 9779)

In [11]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=1)

In [12]:
len(df_train), len(df_val), len(df_test)

(29337, 9779, 9779)

In [13]:
df_train

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
385,115748,1 BDRM Apt-Weekend Sublease,585166,Lilly,Queens,Astoria,40.76434,-73.92132,Entire home/apt,4.709530,4,30,2019-06-16,0.32,1,363
33147,26155827,Greenpoint room,5213686,Charlotte,Brooklyn,Greenpoint,40.73442,-73.95854,Private room,4.262680,5,2,2018-08-09,0.16,1,0
33881,26837745,Great 4 Bedrooms with 4 private baths in ParkS...,199147185,Lou,Brooklyn,Sunset Park,40.66359,-73.99487,Entire home/apt,6.133398,1,33,2019-06-09,2.75,5,113
37208,29562919,Awesome space on your own floor with a Private...,19011946,John,Brooklyn,Bay Ridge,40.63766,-74.02626,Private room,4.605170,3,1,2018-10-25,0.12,2,362
7485,5582283,Cozy bedroom in Brooklyn Sunsetpark,26098783,Sam,Brooklyn,Sunset Park,40.65118,-74.00842,Private room,7.601402,2,0,,0.00,2,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2738,1478315,1 bedroom in heart of Fort Greene,1834942,Tessa,Brooklyn,Clinton Hill,40.69332,-73.96543,Entire home/apt,4.653960,12,11,2017-07-30,0.15,1,15
25619,20505979,L.E.S ROOM Simple Beautiful Clean Apt. 3 Bdr,6725061,Zyanya,Manhattan,Lower East Side,40.71856,-73.98753,Private room,4.248495,4,0,,0.00,1,0
40278,31234360,"Separate PRIVATE ROOM furnished, 5 min to A train",107930075,Ameet,Queens,Woodhaven,40.69034,-73.84611,Private room,3.931826,3,0,,0.00,2,178
17605,13847244,44 floor apt in luxury building near Central Park,52851248,Ella,Manhattan,Theater District,40.76324,-73.98459,Entire home/apt,5.525453,10,1,2016-08-04,0.03,1,0
22406,18094311,Manhattan Bedroom | Skyline Views,3191545,Kyle,Manhattan,Murray Hill,40.74563,-73.97590,Entire home/apt,5.393628,30,1,2018-05-31,0.07,23,362

In [14]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [15]:
df_train.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,115748,1 BDRM Apt-Weekend Sublease,585166,Lilly,Queens,Astoria,40.76434,-73.92132,Entire home/apt,4.709530,4,30,2019-06-16,0.32,1,363
1,26155827,Greenpoint room,5213686,Charlotte,Brooklyn,Greenpoint,40.73442,-73.95854,Private room,4.262680,5,2,2018-08-09,0.16,1,0
2,26837745,Great 4 Bedrooms with 4 private baths in ParkS...,199147185,Lou,Brooklyn,Sunset Park,40.66359,-73.99487,Entire home/apt,6.133398,1,33,2019-06-09,2.75,5,113
3,29562919,Awesome space on your own floor with a Private...,19011946,John,Brooklyn,Bay Ridge,40.63766,-74.02626,Private room,4.605170,3,1,2018-10-25,0.12,2,362
4,5582283,Cozy bedroom in Brooklyn Sunsetpark,26098783,Sam,Brooklyn,Sunset Park,40.65118,-74.00842,Private room,7.601402,2,0,,0.00,2,365

In [16]:
y_train = df_train.price.values
y_val = df_val.price.values
y_test = df_test.price.values

In [17]:
del df_train['price']
del df_val['price']
del df_test['price']

In [18]:
numerical.remove('price')

In [19]:
df_full_train[numerical].corrwith(df_full_train.price)

id                               -0.016372
host_id                          -0.015098
latitude                          0.079057
longitude                        -0.327231
minimum_nights                    0.033435
number_of_reviews                -0.041614
reviews_per_month                -0.059804
calculated_host_listings_count    0.129138
availability_365                  0.098008
dtype: float64

In [20]:
df_full_train[numerical].corrwith(np.expm1(df_full_train.price))

id                                0.010187
host_id                           0.018853
latitude                          0.035097
longitude                        -0.154201
minimum_nights                    0.039181
number_of_reviews                -0.048133
reviews_per_month                -0.050050
calculated_host_listings_count    0.057003
availability_365                  0.081628
dtype: float64

In [21]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import LinearRegression

In [22]:
from sklearn.metrics import mean_squared_error as mse

In [23]:
def test(df_train, y_train, df_val, y_val):
    dv = DictVectorizer(sparse=False)
    X_train = dv.fit_transform(df_train.to_dict(orient='records'))
    X_val = dv.transform(df_val.to_dict(orient='records'))
    model = LinearRegression()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_val)
    print(mse(y_pred, y_val, squared=False))
    print(mse(np.expm1(y_pred), np.expm1(y_val), squared=False))

In [24]:
categorical

['name',
 'host_name',
 'neighbourhood_group',
 'neighbourhood',
 'room_type',
 'last_review']

In [25]:
categorical.remove('host_name')
categorical.remove('name')
numerical.remove('id')
numerical.remove('host_id')

In [26]:
numerical

['latitude',
 'longitude',
 'minimum_nights',
 'number_of_reviews',
 'reviews_per_month',
 'calculated_host_listings_count',
 'availability_365']

In [27]:
test(df_train[numerical+categorical],y_train,df_val[numerical+categorical],y_val)

0.473926690219137
200.83129038993033